$("li.dropdown").hover(
  function(){
      $(this).children(".dropdown").show();
      $(this).children(".dropdown").stop();
      $(this).children(".dropdown").animate({
          opacity:1
      },200)
  },function(){
      $(this).children(".dropdown").stop();
      $(this).children(".dropdown").animate({
          opacity:0
        },400,function(){
            $(this).hide()
        }
      )
  }
)